### ISSUE TITLE
ReadTheDocs documentation builds are taking forever

### ISSUE THREAD

**Issue by tbenthompson** [Quantco/glum#457]
See here: https://readthedocs.org/projects/glum/builds/

The builds are succeeding now but they take 1.5-2 hours. 

Perhaps reading through https://docs.readthedocs.io/en/stable/builds.html to figure out exactly what is happening and then replicating the process locally with docker would help to debug the long build times. Either way, I think this is a fairly urgent problem.

**Comment by MarcAntoineSchmidtQC** [comment]
fixed with mamba
