### ISSUE TITLE
n_jobs parameter is GeneralizedLinearRegressorCV

### ISSUE THREAD

**Issue by kmedved** [Quantco/glum#468]
I'm having an issue where regardless of what I set the n_jobs parameter to in `GeneralizedLinearRegressorCV`, it uses 100% of my processors. Curiously, it still *does* affect the time to fit the model, although in somewhat unpredictable ways, e.g., 5-fold CV with n_jobs of 1 takes 90 seconds to fit, while 5-fold CV with n_jobs of 5 takes ~45 seconds. Both use 100% of cores however (I am running on a 32-core local machine).

Am I misunderstanding what the n_jobs parameter does?

**Comment by kmedved** [comment]
Thanks - I apologize if this should have been obvious.

Do I understand your last line to mean that adding the ability to control the number of cores used for the linear algebra tasks would not be possible/feasible? I would typically use [threadpoolctl ](https://github.com/joblib/threadpoolctl) for this for libraries which don't have native functionality, but this was giving me erratic results/oversubscription errors here.

**Comment by murphyhopfensperger** [comment]
Sorry to bother you, can you tell me the proper way to set OMP_NUM_THREDS?
I copy-pasted something from stackexchange that isn't working for me:
```
import os
os.environ["OMP_NUM_THREADS"] = "1"
```
It seems to work with `n_jobs=1`, but not otherwise.

**Comment by MarcAntoineSchmidtQC** [comment]
@murphyhopfensperger, I believe the way you've set it up should work. When `n_jobs = n`, it will use at least `n` cores, no matter if you've set `OMP_NUM_THREADS` or not. In other words, if your goal is to use one core, you should set `n_jobs = 1` and `OMP_NUM_THREADS = 1`.

If this doesn't clarify things, can you tell us what you are trying to achieve (what is the expected behavior) and what you actually see.

**Comment by murphyhopfensperger** [comment]
What I mean is, I have to share a 128 core machine with a team of other people. If I do nothing to control the usage of cores, I'll gobble up all 128. (Not to mention, 128 threads is number is probably beyond the point of diminishing returns!) I'm trying to use 5 jobs for my 5-fold CV, but the OMP_NUM_THREADS argument seems to stop working when I use n_jobs>1. I don't know much about parallelism, but I guess the os.environ argument doesn't apply to the new processes that are spawned this way?
