### ISSUE TITLE
Does glum implement grouped lasso?

### ISSUE THREAD

**Issue by kxchia1** [Quantco/glum#478]
Sorry in advance if this can be found in the docs. It seems the P1 argument for GeneralizedLinearRegressor can take in only arrays containing either 0 or 1. The main motivation for using grouped lasso is to make sure levels/categories of categorical variables are "retained" or "omitted" altogether during shrinkage. Can this be achieved using the P1 argument?

**Comment by jtilly** [comment]
No, we currently do not implement [group lasso](http://www.columbia.edu/~my2550/papers/glasso.final.pdf). The tag line "High performance Python GLMs with _all_ the features!" is a slight exaggeration 😉 

However, ``P1`` is not constrained to be 0 or 1. You can choose different levels of L1 regularization per coefficient. But that's not enough to get you group lasso, of course.

**Comment by kxchia1** [comment]
thanks for your reply!
