### ISSUE TITLE
Handle upstream removal of _check_param_grid 

### ISSUE THREAD

**Issue by BenBarrettQC** [Quantco/glum#507]
A number of tests are failing against the nightly build of scikit-learn due to the removal of `_check_param_grid` in [this PR](https://github.com/scikit-learn/scikit-learn/pull/21880), which affects `glum` through `dask-ml` (see e.g. [here](https://github.com/dask/dask-ml/blob/30b3deab19755ecd45156ef9cac9fee646615100/dask_ml/model_selection/_search.py#L26)). The relevant places in `glum` are [here](https://github.com/Quantco/glum/blob/96a2be579dc30d68f2efa80bbeef7221ae120849/src/glum_benchmarks/problems.py#L9) and [here](https://github.com/Quantco/glum/blob/96a2be579dc30d68f2efa80bbeef7221ae120849/src/glum_benchmarks/data/create_insurance.py#L6-L7).

We should keep an eye on whether `dask-ml` handles the removal upstream, or otherwise implement a workaround ourselves.

See also #506.

**Comment by lbittarello** [comment]
All tests passing now. :)
