### ISSUE TITLE
Fitting interactions

### ISSUE THREAD

**Issue by peterlee18** [Quantco/glum#515]
Its very good that GLUM can handle the explanatory factors as an untransformed dataframe so the user doesn't have to one-hot encode etc.

However, if one wants to fit interactions then this doesn't work so well. It would be nice to have a feature where you could specify the interactions via a formula string involving the factor columns in the x-dataframe e.g. [factor_1:factor_2,factor_4:factor_6]. Ideally, it would be to indicate that e.g. factor_6 shouldn't be included as a main effect.

The work-around is to create the design matrix for the interaction terms and add that as additional columns as part of the input explanatory variables

**Comment by MarcAntoineSchmidtQC** [comment]
See the related discussion in the sister package tabmat: https://github.com/Quantco/tabmat/issues/145. It would need to be implemented there first and then glum could use this feature.

This would indeed be a nice addition to glum. Implementing this correctly without losing the performance boost of tabmat is not trivial however. I would be happy to help someone who wants to tackle this issue and contribute a PR.

**Comment by peterlee18** [comment]
I have been using GLUM quite extensively and have discovered I like the flexibility of customising the design matrix in terms of interactions and main effects. Often one wants a feature treated differently for the main effect vs the interaction. This can be achieved by specifying the appropriate design matrix. Purely by fit-formula is quite difficult. My default method for specifying the model now is to use a fit-formula to create a design matrix (via formulaic) and then customising this before feeding into GLUM. This works well. So this feature request isn't a high priority.
