### ISSUE TITLE
The README figure is missing labels in GitHub dark mode.

### ISSUE THREAD

**Issue by tbenthompson** [Quantco/glum#533]
The labels are actually there if you squint because they're in a slightly different shade of black than the background. Maybe there's an easy/common way of handling this?

<img width="938" alt="image" src="https://user-images.githubusercontent.com/4241811/161629085-70bc1a27-69aa-4583-96d7-056b51d092b8.png">

**Comment by dhimmel** [comment]
> Maybe there's an easy/common way of handling this?

The way to handle this is to make the entire plot background a color instead of transparent. With matplotlib, I believe this is `axes.facecolor` (currently transparent) and `figure.facecolor` (currently white).

**Comment by jtilly** [comment]
You can also specify different images by theme: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
