### ISSUE TITLE
Setting upper and/or lower bounds for specific coefficients?

### ISSUE THREAD

**Issue by seanlewis08** [Quantco/glum#577]
Hello,
 
I am wondering if the function can allow for lower bounds and upper bounds to be set for individual coefficients in the model to “force” a direction for a particular coefficient? I see there is an upper and lower bound, but I think this sets the bounds for all of the coefficients.
 
I am not sure how to use the A_ineq or B_ineq parameters if this is something that will allow for that functionality.
 An explanation would be helpful.

I am sorry if this is not the forum for this question!

Thank you!
-Sean

**Comment by MarcAntoineSchmidtQC** [comment]
Hi @seanlewis08! The `lower_bounds` and `upper_bounds` arguments actually accept an array-like input. This means the the lower and upper bounds can be set individually for each coefficient.

For instance, one could call `GeneralizedLinearRegressor` in such way:
```python
glm = GeneralizedLinearRegressor(
    family='poisson',
    alpha=0.1, 
    l1_ratio=1,
    lower_bounds=[0, 0, -np.inf, -np.inf]
)
```

In this case, the first and second coefficients will have 0 as a lower bound while the third and fourth won't be bound.
If this answers your question, please close this issue.

**Comment by seanlewis08** [comment]
Thank you!
