### ISSUE TITLE
M1 wheels?

### ISSUE THREAD

**Issue by sid-kap** [Quantco/glum#602]
It looks like CI is configured to build arm64 wheels for MacOS:
https://github.com/Quantco/glum/blob/f8765f1c11e0ddfd2f65e229c9ba9edf618550a4/.github/workflows/conda-build-macos.yml#L20-L21

But I don't see them listed on [PyPI](https://pypi.org/project/glum/#files). Are there plans to start publishing M1 wheels? Is there anything I could do to help?

(And same question for tabmat?)

**Comment by xhochy** [comment]
The referenced code is only relevant for conda packages. I'm adding Apple Silicon builds for `tabmat` in https://github.com/Quantco/tabmat/pull/218

**Comment by sid-kap** [comment]
Thanks so much for looking into this!!
