### ISSUE TITLE
What does the alpha parameter do when using variable regularization?

### ISSUE THREAD

**Issue by kmedved** [Quantco/glum#605]
I have a somewhat simple question I think. From reading the docs here (https://glum.readthedocs.io/en/latest/tutorials/regularization_housing_data/regularization_housing.html), I see how one can use the P1 or P2 parameter to set variable L1/L2 regularization. However, in the example, an `alpha` parameter is also set. What is this parameter doing?

I normally use Glum by setting an L1 ratio and an `alpha`, which controls the ratio between L1 and L2 regularization. That makes sense to me, but I'm not understanding what the `alpha` parameter does when you're setting the L1 levels directly?

And if I don't set an `alpha` value, what does it default to when setting a P1 value?

**Comment by lbittarello** [comment]
Hi @kmedved,

Thanks for the question. We always multiply the penalty matrices, `P1` and `P2`, by the regularization strength, `alpha` – see [here](https://github.com/Quantco/glum/blob/d5c4479f2f8df587a002b7226354311513c3eb05/src/glum/_glm.py#L515), for example. If you don't set `alpha`, it defaults to unity – see [here](https://github.com/Quantco/glum/blob/d5c4479f2f8df587a002b7226354311513c3eb05/src/glum/_glm.py#L2494), for example – so your P1 will be used as is.

**Comment by lbittarello** [comment]
Closing as answered. Feel free to reopen!
