### ISSUE TITLE
`-march` is not cross-plaform

### ISSUE THREAD

**Issue by david-cortes** [Quantco/glum#607]
Same issue as in https://github.com/Quantco/tabmat/issues/223

The setup script tries to set argument `-march=native`:
https://github.com/Quantco/glum/blob/a405fd73bdb959f533358027201ebb641a60f700/setup.py#L37

But this argument is not accepted by GCC in platforms like ARM and PPC. Instead, those platforms use `mcpu` (at least for GCC in linux), so to achieve the same thing, it should use `-mcpu=native`.

**Comment by jtilly** [comment]
One way around this is to set the environment variable 
```
GLM_ARCHITECTURE=default
```
before running `pip install`.

`"default"` would arguably have been a better default than `"native"`.

**Comment by david-cortes** [comment]
@xhochy I think the changes in the PR would still make it fail to install on linux on platforms like ppc64el. Also, in linux-aarch64, even if it doesn't fail, it wouldn't make it use the highest instruction level like it would on amd64.

What would tou think about making a check for switching between `-march=native` and `-mcpu=native` depending on the platform?

**Comment by xhochy** [comment]
I would prefer to remove the `-march=native` code completely. Most users will use the binary wheels or conda packages. People that opt for compiling on their own due to performance will have sufficient knowledge to tune C(XX)FLAGS.
