### ISSUE TITLE
Difference between `GeneralizedLinearRegressor` and `GeneralizedLinearRegressorCV` for finding best alpha

### ISSUE THREAD

**Issue by miaow27** [Quantco/glum#608]
Hi there, 

I am currently using `GeneralizedLinearRegressorCV` for L1-penalized regression for variable selection purpose. Currently, I am leaving everything as default which means there will be 100 alpha being tried on 5-cv folds resulting in 500 times glm repeated. 

This process is extremely slow for my dataset and I want to improve it. 
I notice `GeneralizedLinearRegressor` also allows specifying a list of alphas to try. I am wondering if I can use that as an alternative for better run time. 

Also, what is your criteria for finding best alpha for `GeneralizedLinearRegressor`? 
Thanks!

**Comment by lbittarello** [comment]
Closing as answered. Feel free to reopen!

**Comment by miaow27** [comment]
Thank you!!! Very helpful suggestions.
