### ISSUE TITLE
Convergence issue for L1-penalized regression

### ISSUE THREAD

**Issue by miaow27** [Quantco/glum#609]
Hi there, 

We have some convergence issue when trying to use a L1-penalized GLM. the error message says `..._solvers.py: 352: ConvergenceWarning: IRLS failed to converge. Increase the maximum number of iterations max_iter (currently 1).`

Is this something concerning? What can we change when specifying the `GeneralizedLinearRegressor`?

Thanks,
Miao

**Comment by lbittarello** [comment]
Same here: sorry for the late response!

Looking at your warning, you set `max_iter` to one? Any optimisation algorithm needs many more iterations to converge (hence the default hundred iterations).

**Comment by lbittarello** [comment]
Closing as answered. Feel free to reopen!

**Comment by miaow27** [comment]
Thank you!
