### ISSUE TITLE
Computation of scores with intercept fails because `scipy.sparse.hstack` does not handle `SplitMatrix` 

### ISSUE THREAD

**Issue by MatthiasSchmidtblaicherQC** [Quantco/glum#610]
I am trying to compute the covariance matrix of the coefficients of an unregularised GLM for a split design matrix. The score computation gives the error `ValueError: blocks[0,:] has incompatible row dimensions. Got blocks[0,1].shape[0] == 1, expected n.` where [it stacks the matrices ](https://github.com/Quantco/glum/blob/a405fd73bdb959f533358027201ebb641a60f700/src/glum/_distribution.py#L528) for the intercept and the offer coefficients. See minimal example:
```
# %%
import numpy as np
import tabmat as tm

from glum._glm import GeneralizedLinearRegressor
# %%
rng = np.random.default_rng(123) 

X = tm.SplitMatrix(
    matrices=[
      tm.DenseMatrix(rng.normal(size=(10, 2))),
      tm.SparseMatrix(rng.integers(0, 2, size=(10, 2)))
    ]
)
y = rng.poisson(1, size=10)
mu = y + rng.normal(0.1, size=10)
w=np.ones_like(y)
# %%
model.family_instance._score_matrix(
    link=model.link_instance,
    y=y,
    X=X,
    mu=mu,
    sample_weight=w,
    dispersion=1,
    fit_intercept=True
) # error
# %%
model.family_instance._score_matrix(
    link=model.link_instance,
    y=y,
    X=X,
    mu=mu,
    sample_weight=w,
    dispersion=1,
    fit_intercept=False
) # returns a SplitMatrix
# %%
```
I could solve this locally by transforming the split matrix to an array first, i.e. changing the following lines
```
        if fit_intercept:
            if sparse.issparse(X) or isinstance(X, (SplitMatrix, CategoricalMatrix)):
                XW = X.multiply(W).A
            else:
                XW = np.multiply(X, W)
            return np.hstack((W, XW))
```
Happy to make an PR with this fix, but also happy to hear if there is a better way that manages to preserve the split matrix structure while stacking horizontally.

**Comment by MarcAntoineSchmidtQC** [comment]
Thanks for reporting this bug @MatthiasSchmidtblaicherQC. I prefer not transforming the splitmatrix into an array because the data would then have a much greater memory requirement. However, the fix should be quite easy. I should be able to make a PR later today to fix this.

**Comment by MatthiasSchmidtblaicherQC** [comment]
Thanks Marc, looking forward to seeing the code :).
