### ISSUE TITLE
Unused import line

### ISSUE THREAD

**Issue by adityagoel4512** [Quantco/glum#614]
I believe the items imported in https://github.com/Quantco/glum/blob/main/src/glum/_cd_fast.pyx#L24 might be unused. Would it be safe to delete this line or is there a consequence I am missing? In the short term the nightly build of scikit-learn has changed the type signatures of the imported functions in https://github.com/scikit-learn/scikit-learn/pull/25791/files which can cause linking issues when using glum within an environment with the nightly scikit-learn build.

**Comment by xhochy** [comment]
> Would it be safe to delete this line or is there a consequence I am missing?

I think it would safe to delete. Happy to receive a first PR from you here :)

**Comment by adityagoel4512** [comment]
https://github.com/Quantco/glum/pull/615 !

**Comment by lbittarello** [comment]
Closed via #615.
