### ISSUE TITLE
GeneralizedLinearRegressorCV - Is it possible to use custom defined folds?

### ISSUE THREAD

**Issue by seanlewis08** [Quantco/glum#690]
cv : int, cross-validation generator or Iterable, optional (default=None)
        Determines the cross-validation splitting strategy. One of:

        - ``None``, to use the default 5-fold cross-validation,
        - ``int``, to specify the number of folds.
        - ``Iterable`` yielding (train, test) splits as arrays of indices.

        For integer/``None`` inputs, :class:`KFold` is used
        
It appears that it is not possible to feed custom folds into the GeneralizedLinearRegressorCV? Am I reading this correctly or am I misunderstanding?

**Comment by lbittarello** [comment]
Hi @seanlewis08! You can feed custom folds by implementing them as an iterable in accordance with scikit-learn's [`splitter` API](https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators). You might find [`PredefinedSplit`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.PredefinedSplit.html#sklearn.model_selection.PredefinedSplit) particularly helpful.
