### ISSUE TITLE
Trouble with importlib library when installing using pip3

### ISSUE THREAD

**Issue by mattmills49** [Quantco/glum#733]
Hi there. I am attempting to load this package after install and running into the following error:
```python
[~/Documents/Data](https://file+.vscode-resource.vscode-cdn.net/Users/mm/Documents/Data%20Science/Blog%20Posts/weighting_sampling/~/Documents/Data) Science/Blog Posts/weighting_sampling/lib/python3.7/site-packages/glum/__init__.py in <module>
----> 1 import importlib.metadata
      2 
      3 from ._distribution import (
      4     BinomialDistribution,
      5     ExponentialDispersionModel,

ModuleNotFoundError: No module named 'importlib.metadata'
```
I'm running a virtual environment using python version `3.7.3` in Visual Studio. I believe `pip` is trying to install glum version `2.6.0`.

I have tried to install both `importlib` and `importlib.metadata` and neither has fixed the issue. I know on the instructions page it says to use conda to install but I'm really only familiar with using `pip3` and virtual environments. Is this an issue others have seen? Is it not possible to install the package outside of conda? Any and all help is much appreciated.

**Comment by jtilly** [comment]
In #701, we should have bumped the minimally support Python version to 3.8 (when `importlib.metadata` was introduced; the typical workaround is to install [`importlib_metadata`](https://pypi.org/project/importlib-metadata/)). Note that as of the next `glum` release, the minimally supported Python version will be 3.9.

You should be able to get a Python 3.7 compatible version of `glum` by installing

```
pip install glum==2.5.2
```

**Comment by mattmills49** [comment]
Thanks so much @jtilly ! That worked and everything seems to be working. I guess I didn't realize how behind my python install was haha.
