### ISSUE TITLE
ElasticNet in Glum 2.6.0 is twice as slow as Scikit-learn 1.3.2 

### ISSUE THREAD

**Issue by carlosg-m** [Quantco/glum#736]
- **~8 seconds** in Glum vs. **~4 seconds** in  Scikit-learn
- Same amount of memory used 
- **~0.015 RMSE**, using similar hyperparameters

**Results plot**
![image](https://github.com/Quantco/glum/assets/55836583/fb89a27b-6fd6-415e-9dd3-dee0a51dc4fa)

**Gloom 2.6.0** 
![image](https://github.com/Quantco/glum/assets/55836583/d4a1711f-7aa8-4f41-b8e8-df89635ab9aa)
![image](https://github.com/Quantco/glum/assets/55836583/d5ac1608-4135-450a-8469-60e934b19236)

**Scikit-learn 1.3.2** 
![image](https://github.com/Quantco/glum/assets/55836583/dbf05b2b-8e66-4e42-9074-a972dc85c9be)
![image](https://github.com/Quantco/glum/assets/55836583/e2cbd9e3-fa59-4cb6-8b81-1ee7f5e86f72)

**Comment by carlosg-m** [comment]
@Badr-MOUFAD, thank you for the extra information. I've tried fitting skglm to a couple of series but the benefit did not justify altering the model since we're close to deploy the project into production.

But I'm going to keep the library in mind for the next phases of this particular project. The initiative and motivation is fantastic and we need more libraries like gloom or skglm to close the GLM gap between Python and R.

If you want more information about what we are doing there is a recap in this github issue https://github.com/scikit-learn/scikit-learn/discussions/27886.

**Comment by MatthiasSchmidtblaicherQC** [comment]
Thanks for the Colab @carlosg-m. As you guessed, the performance difference between glum and sklearn comes indeed from the `precompute` argument. In the example, I get:
~11s with ElasticNet and `precompute=True`.
~10s with skglm (thanks for the pointer @Badr-MOUFAD).
~30s with glum.
~50s with ElasticNet and precompute=False
See a more stripped down example below, the ranking seemed relatively stable in the parameter configurations that I tried.

_Some background_:
`D` in " `X'D X` in GLM fitting generally depends on the inverse derivative of the linear prediction and must be recomputed at each iteration of IRLS. 

In the case of a (homoscedastic) normal distribution and identity link, `D` is just the identity, so `A` can be precomputed as `X'X`. Unlike `ElasticNet`, `glum`  has not been optimized for this case and you are indeed better off using one of the other libraries for maximal performance. We always welcome contributions to glum, in case that you want to add the precompute option :).

```
# %%
import numpy as np
import pandas as pd
import skglm

from sklearn.linear_model import ElasticNet
from glum import GeneralizedLinearRegressor
from timeit import timeit

# %%
n = 10_000
k = 10
rng = np.random.default_rng(123)
# %%
beta = rng.normal(size=k)
X = pd.DataFrame({f"x{i}": rng.normal(size=n) for i in range(k)})
y = X @ beta + rng.normal(size=n)
# %%
alpha = 0.01 q
l1_ratio = 0
# %%

model_sklearn = ElasticNet(
    alpha=alpha,
    l1_ratio=l1_ratio,
    precompute=True,
    max_iter=1000,
    copy_X=False,
    selection="cyclic",
    fit_intercept=False,
)

model_glum = GeneralizedLinearRegressor(
    alpha=alpha,
    l1_ratio=l1_ratio,
    max_iter=1000,
    copy_X=False,
    selection="cyclic",
    fit_intercept=False,
    family="normal",
    solver="irls-cd",
    link="identity",
)

model_sklearn_no_precompute = ElasticNet(
    alpha=alpha,
    l1_ratio=l1_ratio,
    precompute=False,
    max_iter=1000,
    copy_X=False,
    selection="cyclic",
    fit_intercept=False,
)

model_skglm = GeneralizedLinearEstimator(
    datafit=skglm.datafits.Quadratic(),
    penalty=skglm.penalties.L1_plus_L2(alpha=0.001, l1_ratio=0.5),
    solver=skglm.solvers.GramCD(max_iter=1000, fit_intercept=False)
)
# %%
%timeit model_sklearn.fit(X=X, y=y)
# %%
%timeit model_glum.fit(X=X, y=y)
# %%
%timeit model_sklearn_no_precompute.fit(X=X, y=y)
# %%
%timeit model_skglm.fit(X=X, y=y)
# %%
```
