### ISSUE TITLE
Clarify effect of `scale_predictors` on penalization in docstring

### ISSUE THREAD

**Issue by mayer79** [Quantco/glum#775]
When using penalized regression, by default, H2o applies penalties to internally standardized features. This is convenient because users do not need to scale the input manually to ensure fair application of penalties. 

How is it done with glum? It seems that features are internally scaled. Are penalties applied to standardized coefficients or to the original coefficients?

**Comment by MatthiasSchmidtblaicherQC** [comment]
Whether penalties are applied to standardized features is governed by the `scale_predictors` argument, see [here](https://github.com/Quantco/glum/blob/d65ac0d7305e408224c062d57f80389c3fb638f8/src/glum/_glm.py#L2984). To be precise, features are always standardized, but, in case that `scale_predictors=False`, the penalty is adjusted as if there was no standardization.

**Comment by mayer79** [comment]
Oh, I see, thanks!

I am typically interested in getting unscaled coefficients in ` coef_table()`, and at the same time applying penalties to an (internally) scaled design matrix to ensure that all features are treated equally. If I got the docu of `scale_predictors` right, this combination is not easily available?

**Comment by MatthiasSchmidtblaicherQC** [comment]
No problem! 

The behavior that you describe should be the default, the coefficients are ["unstandardized" again](https://github.com/Quantco/glum/blob/d65ac0d7305e408224c062d57f80389c3fb638f8/src/glum/_glm.py#L3049). You can also check this with an example:
```
import pandas as pd
import numpy as np

from glum import GeneralizedLinearRegressor

rng = np.random.default_rng(42)

X = pd.DataFrame({"x1": rng.normal(size=100), "x2": rng.normal(size=100)})
y = df["x1"] + df["x2"] + rng.normal(scale=0.1, size=100)
X["x2"] *= 100 

GeneralizedLinearRegressor(alpha=0.1, scale_predictors=True).fit(X, y).coef_ # second coef is smaller by order of -2
```

> what does "adjusted as if..." mean?

The standardization is also applied to the penalty matrix so that score equations are unchanged up to an affine transformation compared to no standardization (this is done for numerical stability). You can have a look at `_standardize` for the details if you are interested.

**Comment by mayer79** [comment]
Fantastic, thanks a lot for the explanation and the example!

**Comment by mayer79** [comment]
Should we mention in the docu of `scale_predictors` that the default (`False`) will scale the penalties, i.e., if one wants to penalize each feature equally, one would need to set `scale_predictors=True`?

**Comment by MatthiasSchmidtblaicherQC** [comment]
Yes, I think this is worth mentioning, thanks for the input.

**Comment by MatthiasSchmidtblaicherQC** [comment]
I adjusted the docstring, see https://github.com/Quantco/glum/pull/778. Can you have a look?
