### ISSUE TITLE
Benchmark removal of libblas dependency

### ISSUE THREAD

**Issue by MatthiasSchmidtblaicherQC** [Quantco/glum#787]
We already don't install libblas on macOS because it is not available there. We should benchmark if it brings any benefit to Windows or ubuntu machines and, if not, remove it entirely. This would obviate the need for a separate environment specification on macOS.

**Comment by stanmart** [comment]
If we were to switch to pixi for installing the dev environment, then we could do [platform-specific dependencies](https://pixi.sh/v0.17.1/advanced/multi_platform_configuration/) and [lockfiles](https://pixi.sh/v0.20.0/features/lockfile/) both of which quite useful for reproducible benchmarking. Would this be an option in the future?

**Comment by MarcAntoineSchmidtQC** [comment]
I agree that pixi would be great for that use case. However, I don't think I would switch to pixi to build the package (not sure if that would even be possible). This means adding another build tool without replacing one. I'm not against it, but it's not super clear the effort is worth it.

**Comment by MarcAntoineSchmidtQC** [comment]
I will close this issue, but feel free to move the pixi conversation to another issue!
