### ISSUE TITLE
Question: Differences in VC matrix

### ISSUE THREAD

**Issue by mayer79** [Quantco/glum#823]
The variance-covariance estimates (and the standard errors derived from their diagonal) can differ by quite some margin (10-20%) from those of statsmodels, see the example below.  Is this as expected?

If I am not wrong, glum uses n/(n-p-1) times the inverse of the Fisher information matrix. Not sure what statsmodels is doing, but it seems to be identical to R's `glm()`, which uses "dispersion * (X'X)^-1", where the inverse is calculated from the R part of the QR decomposition, and dispersion depends on the family. For the normal family, it is sum(residuals^2) / (n-p-1).

### Glum

```py
import numpy as np
from glum import GeneralizedLinearRegressor
import statsmodels.api as sm

n = 100
rng = np.random.default_rng(0)
X = rng.standard_normal((n, 5))
y = (X[:, 0] > 0) + rng.uniform(size=n)

# Glum
model = GeneralizedLinearRegressor(alpha=0).fit(X, y)
_ = model.covariance_matrix(X=X, y=y, store_covariance_matrix=True)
model.coef_table()
```

![image](https://github.com/user-attachments/assets/ad6eea1f-1548-4083-a6ac-93c33b2809f7)

### Statsmodels

```py
# Statsmodels
model2 = sm.GLM(y, sm.add_constant(X)).fit()
model2.summary()
```

![image](https://github.com/user-attachments/assets/a3039851-37c9-4e07-9d99-1b9e5a2e0653)

### R

```r
library(arrow)

X <- read_parquet("X.parquet")
y <- read_parquet("y.parquet")

fit <- glm(y ~ ., data = data.frame(y = y[[1]], X))
summary(fit)


            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.99812    0.04283  23.304  < 2e-16 ***
X0           0.46044    0.04666   9.867 3.52e-16 ***
X1           0.02333    0.04118   0.567   0.5724    
X2           0.09017    0.04593   1.963   0.0526 .  
X3          -0.02790    0.03703  -0.753   0.4530    
X4          -0.05887    0.03817  -1.543   0.1263    
```

Versions: 
- glum 3.0.2
- statsmodels 0.14.1

**Comment by lbittarello** [comment]
Thanks for the issue and for the MRE!

Glum and Statsmodels produce the same standard errors, except for a correction for the degrees of freedom in the model. Glum uses `n / (n - k - 1)`, where `k` is the number of features in the model, whereas Statsmodels doesn't correct homoscedastic standard errors at all. To verify this:

```python
import glum
import numpy as np
import statsmodels.api as sm

n = 100
rng = np.random.default_rng(0)

X = rng.standard_normal((n, 5))
y = (X[:, 0] > 0) + rng.uniform(size=n)

dof_corr = len(y) / (len(y) - X.shape[1] - 1)

glum_se = (
    glum.GeneralizedLinearRegressor(alpha=0)
    .fit(X, y)
    .std_errors(X=X, y=y, robust=False)
)

sm_se = sm.GLM(y, sm.add_constant(X)).fit(cov_type="nonrobust").bse

np.testing.assert_array_almost_equal(glum_se, sm_se * np.sqrt(dof_corr))
```

The standard errors are equal up to fifteen digits. :)

**Comment by mayer79** [comment]
You are faster than the wind, thanks! I have also added the results from R's `glm()`.

**Comment by mayer79** [comment]
@lbittarello I am probably making a very stupid mistake, but why are these standard errors again different from statsmodels?

```py
VC = model.covariance_matrix(X=X, y=y, store_covariance_matrix=True)
np.sqrt(VC.diagonal() / dof_corr)

# array([0.0434066, 0.0405607 , 0.03731663, 0.04683188, 0.03192106, 0.03436726])
```

**Comment by lbittarello** [comment]
Glum computes robust standard errors by default. You should get the same SEs with

```python
VC = model.covariance_matrix(X=X, y=y, store_covariance_matrix=True, robust=False)
np.sqrt(VC.diagonal() / dof_corr)
```

**Comment by mayer79** [comment]
Ahaaaa, thanks again!

**Comment by lbittarello** [comment]
I'm closing this issue as resolved, but feel free to reopen if you have more questions!
