### ISSUE TITLE
How to avoid any unnecessary copies from numpy -> tabmat / glum, including categoricals?

### ISSUE THREAD

**Issue by mlondschien** [Quantco/glum#838]
We are working with a large dataset that fits only once into memory. We have (in memory) a `np.ndarray` of ~ 90mio x 3k `float32`s, a list of `feature_names`, and a list of tuples `(categorical_name, num_categories)` of features that are categorical, with possible categories `0, ..., num_categories - 1`. No missings. Our current code looks like this:

```python
data: np.ndarray
model = GeneralizedLinearRegressor(...)

# As `data` is one block, this should not do any BlockManager shenanigans.
data = pd.DataFrame(data, columns=feature_names, copy=False)

# This might trigger some BlockManager shenanigans
data[categorical_names] = data[categorical_names].astype("category")

# This needs to be done as the train/test data is not an iid split, so we expect
# many unseen categories.
for (category_name, num_categories) in [("a", 2), ....]:
    data[category_name] = data[category_name].cat.set_categories(list(range(n_categories)))

model.fit(data, y)
```

Is there an alternative going directly from the `np.ndarray` to a `tabmat.SplitMatrix` without any copies (for the non-categorical part)? Pseudo-code:
```python
data_continuous = tabmat.from_csc(data[:, continuous_mask], column_names=...)
data_categorical = ???
data = tabmat.concat([data_continuous, data_categorical])
```

**Comment by stanmart** [comment]
`tabmat.CategoricalMatrix` stores category codes as `np.int32`. If I understand you correctly, they are stored as `float32` in your `data: np.ndarray`. Therefore, even though they look like category codes, a conversion needs to happen unfortunately.

Another thing is that `tabmat.from_csc` is designed for creating a `tabmat.SplitMatrix` from a `scipy.sparse.csc_matrix`, I don't think it will work for a numpy array. If you really want to avoid a copy for that part, and are fine with storing all your columns as dense, you could do
```python
data_continuous = tabmat.DenseMatrix(data[:, continuous_mask], column_names=...)
```

**Comment by mlondschien** [comment]
Thanks @stanmart .

I am not so concerned about the categorical part. This is comparably small. The continuous data is dense.

Can I create a `tabmat.CategoricalMatrix` with pre-specified categories without going through pandas? How do I concat the `CategoricalMatrix` with the `DenseMatrix`?

**Comment by stanmart** [comment]
> Can I create a tabmat.CategoricalMatrix with pre-specified categories without going through pandas?

Currently, not really. The `CategoricalMatrix` stores the data in a `pandas.Categorical`, so it will create a pandas series even if you pass it a numpy array. (The situation will improve soon thanks to [tabmat #370](https://github.com/Quantco/tabmat/pull/370). Maybe we should even expose a `from_codes` constructor.) Right now your best option is to create a `pandas.Categorical` by hand and pass that to `CategoricalMatrix`. Something li,ke

```python
categorical_matrices = []
for ind in categorical_indices:
    cat = pd.Categorical.from_codes(data[:, ind].astype(np.int32), categories=...)
    categorical_matrices.append(tabmat.CategoricalMatrix(cat, column_name=...))
```

Note, that each `CategoricalMatrix` represents exactly one categorical column.

> How do I concat the CategoricalMatrix with the DenseMatrix?

The constructor of `SplitMatrix` accepts a list of tabmat matrices, so you can do

```python
tabmat.SplitMatrix([data_continuous] + categorical_matrices)
```

or just use `hstack` and then you can you don't even have to convert the dense part by hand, but assigning the names is more annoying:

```python
tabmat.hstack([data[:, continuous_mask]] + categorical_matrices)
```

**Comment by stanmart** [comment]
Feel free to reopen if anything related comes up :)
