### ISSUE TITLE
Attach `col_stds` and `col_means` to fitted `GeneralizedLinearRegressor`

### ISSUE THREAD

**Issue by mlondschien** [Quantco/glum#870]
These are computed anyways and nice to have for downstream analysis.

**Comment by stanmart** [comment]
Can you elaborate a bit on the downstream analysis use case? I'm not against adding these new attributes, but it is also a commitment to keep them there in the future.

**Comment by mlondschien** [comment]
I mostly want to recover `alpha * l1_ratio * np.abs(glm.coef_ * glm.col_stds_)` and `alpha * (1 - l1_ratio) * np.square(glm.coef_ * glm.col_stds_)`. I don't care about the means.
